[package]
name = "bevy_ahoy"
authors = ["Jan Hohenheim <jan@hohenheim.ch>"]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0 "
description = "A fun 3D Kinematic Character Controller for Bevy + Avian + BEI."
readme = "readme.md"
repository = "https://github.com/janhohenheim/bevy_ahoy"
keywords = ["kcc", "character", "controller", "source", "quake"]
categories = ["game-development"]
include = ["/src", "/license*", "/examples"]

[features]
default = ["pickup"]
serialize = ["dep:serde", "avian3d/serialize", "bevy_math/serialize", "avian_pickup?/serialize"]
pickup = ["dep:avian_pickup"]

[dependencies]
avian3d = { version = "0.7", default-features = false, features = ["parry-f32", "3d", "f32"] }
bevy_ecs = { version = "0.19", default-features = false }
bevy_app = { version = "0.19", default-features = false }
bevy_derive = { version = "0.19", default-features = false }
bevy_utils = { version = "0.19", default-features = false }
bevy_math = { version = "0.19", default-features = false }
bevy_reflect = { version = "0.19", default-features = false }
bevy_transform = { version = "0.19", default-features = false }
bevy_time = { version = "0.19", default-features = false }
bevy_enhanced_input = { version = "0.26", default-features = false }
tracing = { version = "0.1", default-features = false }
# Pending PR: https://github.com/janhohenheim/avian_pickup/pull/33
avian_pickup = { git = "https://github.com/alexandre-v1/avian_pickup", rev = "5c8d42feedae13ed4b71a8e5686fa0ae5d81a5a5", default-features = false, optional = true }
serde = { version = "1", default-features = false, features = ["derive"], optional = true }

[dev-dependencies]
bevy = { version = "0.19", features = ["track_location", "dynamic_linking", "file_watcher"] }
# Pinned to `main`, pending 0.14.0 release
bevy_trenchbroom = { git = "https://github.com/Noxmore/bevy_trenchbroom", rev = "ca9bc9e8b4a9ce57c48966330bce4b65b4fd8353", features = ["avian_f32"] }
# Pinned to `main`, pending new release
bevy_mod_mipmap_generator = { git = "https://github.com/DGriffin91/bevy_mod_mipmap_generator", rev = "5f9c33a058fac212d568ac97b26ea1aa67489687" }
avian3d = "0.7.0"
# Pending PR: https://github.com/aevyrie/bevy_framepace/pull/77
bevy_framepace = { git = "https://github.com/hacknus/bevy_framepace", rev = "4a950ca526bd4fb56d03b7caf28a04f2bbac2123" }
# Pending PR: https://github.com/janhohenheim/bevy_fix_cursor_unlock_web/pull/4
bevy_fix_cursor_unlock_web = { git = "https://github.com/andogq/bevy_fix_cursor_unlock_web", rev = "858e6e3ab5caaa68011c747ce28c58e99e01f20e" }
wasm-bindgen = "=0.2.108"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.3", features = ["wasm_js"] }

[package.metadata.bevy_cli.unstable]
#web-multi-threading = true

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[lints.rust]
# missing_docs = "warn"
unused_qualifications = "warn"

[lints.clippy]
too_many_arguments = "allow"
type_complexity = "allow"
needless_lifetimes = "allow"
doc_markdown = "warn"
manual_let_else = "warn"
match_same_arms = "warn"
redundant_closure_for_method_calls = "warn"
redundant_else = "warn"
semicolon_if_nothing_returned = "warn"
undocumented_unsafe_blocks = "warn"
unwrap_or_default = "warn"
nonstandard_macro_braces = "warn"
ptr_as_ptr = "warn"
ptr_cast_constness = "warn"
ref_as_ptr = "warn"
too_long_first_doc_paragraph = "allow"
allow_attributes = "warn"
allow_attributes_without_reason = "warn"

[package.metadata.docs.rs]
rustdoc-args = ["-Zunstable-options", "--generate-link-to-definition"]
all-features = true
